### ISSUE TITLE
Calling text to speech service using REST SDK

### ISSUE THREAD

**Issue by vinaykumar0787** [microsoft/cognitive-services-speech-sdk-js#93]
Hi, 

I am trying to use the Text to speech service(REST) from Azure Cognitive, and am successful when trying using Postman, "https://**.tts.speech.microsoft.com/cognitiveservices/v1", and getting a mpga file. 
When trying with AJAX, the blob downloaded seems corrupted, or may be I am setting the content-type wrong.
Is there any way the SDK could help? I couldn't find a sample for that.

Thanks

**Comment by pankopon** [comment]
Hi, we can look into this - could you please provide the relevant part of your code for review?

**Comment by yinhew** [comment]
Hi, @vinaykumar0787 

Here is our official JS sample code to call Text-To-Speech (REST):
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-nodejs-text-to-speech
Could you please give a try to this?

Thanks

**Comment by vinaykumar0787** [comment]
Hi, @yinhew 

Thanks for the reply. Actually your solution is good, but its NodeJs, and I have already tried that with .NET Code, but the thing is that its server side. So my Web app, will have to call the API, which in turn call the Azure service. I wanted to directly call it from Web Javascript saving me time. Below is the code for reference I tried(@pankopon ). This call works well with Postman and file gets played:

$.ajax({
        type: 'POST',
        url: 'https://**.tts.speech.microsoft.com/cognitiveservices/v1',
        beforeSend: function(request) {
          request.setRequestHeader("Authorization", "Bearer " + authorizationToken);
          request.setRequestHeader("X-Microsoft-OutputFormat", "audio-16khz-32kbitrate-mono-mp3");
          request.setRequestHeader("Content-Type", "application/ssml+xml");
        },
        data: data,
        responseType: "blob",
        success: function(data) {
                console.log(data);
                var audioBlob = new Blob([data], {type: "audio/mpeg"});
                var audioURL = URL.createObjectURL(audioBlob);
                if (audioURL.length > 5){

                    var link=document.createElement('a');
                    link.href=audioURL;
                    link.download="filename.mpga";
                    link.click();
                      }
                  }else{
                    console.log("An error occurred getting and playing the audio.")
                  }
            },    
            error: function() {
                alert("TTS failed");
            }
      });

**Comment by yinhew** [comment]
@vinaykumar0787 thanks for providing the working client JS code.
We will consider adding a client JS code as the sample code with your code as the reference.
So your issue is solved?

**Comment by vinaykumar0787** [comment]
@yinhew 
Sorry for the confusion. This Ajax request I have attached is actually not working. The file gets downloaded on browser, but it seems corrupted.
When I replicate the same call on Postman manually, a working mpeg file gets downloaded.
So, the issue is not solved. I hope I am able to clarify this time. Here is a link I referred:
"https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech"

**Comment by yulin-li** [comment]
@vinaykumar0787 
Thanks for reaching out. As request in ajax will always try to parse the response to text string, so the saved data is in wrong type. I noticed you try to set the responseType by `responseType: "blob"`, which seems not workong. An effective method is to modify xhrFields as 

```js
xhrFields: {
      responseType: 'blob'
},
```

I tested is and it works on my machine. You can have a try.

The codes will be changed to 

```js
$.ajax({
        type: 'POST',
        url: 'https://**.tts.speech.microsoft.com/cognitiveservices/v1',
        beforeSend: function(request) {
          request.setRequestHeader("Authorization", "Bearer " + authorizationToken);
          request.setRequestHeader("X-Microsoft-OutputFormat", "audio-16khz-32kbitrate-mono-mp3");
          request.setRequestHeader("Content-Type", "application/ssml+xml");
        },
        data: data,
        xhrFields: {
                 responseType: 'blob'
        },
        success: function(data) {
                console.log(data);
                var audioBlob = new Blob([data], {type: "audio/mpeg"});
                var audioURL = URL.createObjectURL(audioBlob);
                if (audioURL.length > 5){

                    var link=document.createElement('a');
                    link.href=audioURL;
                    link.download="filename.mpga";
                    link.click();
                      }
                  }else{
                    console.log("An error occurred getting and playing the audio.")
                  }
            },    
            error: function() {
                alert("TTS failed");
            }
      });
```

**Comment by vinaykumar0787** [comment]
@yulin-li 
Thanks for the solution, it really helps.
